### ISSUE TITLE
Cadastro Lote | Ajustar CSS

### ISSUE THREAD

**Issue by Joao-Pedro-MW** [Joao-Pedro-MW/NANO-G#46]
Ajustar CSS do modo que mostra as informações.

Deixar mais responsivo pois quando reduzimos a largura do navegador o campo que mostra a unidade de medida some.
Reduzir o espaçamento entre o lado direito e esquerdo, pode ser mais junto

**Comment by Joao-Pedro-MW** [comment]
Ajustar também a largura onde selecionamos o item 🥱

**Comment by Heblg** [comment]
acredito que esteja tudo certo
