### ISSUE TITLE
Troca de senha

### ISSUE THREAD

**Issue by Joao-Pedro-MW** [Joao-Pedro-MW/NANO-G#50]
Montar lógica para a troca de senha ao momento q um usuário recém criado tentar logar no sistema.
 @AlynneAyumi montar a lógica no banco de dados e me passar para eu fazer a programação

**Comment by Joao-Pedro-MW** [comment]
@Heblg favor criar as telas conforme foi solicitado no whatsapp.

**Comment by Heblg** [comment]
ta pitel

**Comment by Joao-Pedro-MW** [comment]
Obrigatório a troca de login no primeiro login e agora os usuários podem trocar sua senha

**Comment by Joao-Pedro-MW** [comment]
@Heblg  fazer um botão escrito 'Trocar Senha' abaixo do botão de sair

**Comment by Heblg** [comment]
feito
